###

GET http://localhost:3000/v1/users
Content-Type: application/json

###

GET http://localhost:3000/v1/user/5d77e850f35d0a11e80b9004
Content-Type: application/json

###

POST http://localhost:3000/v1/user
Content-Type: application/json

{
    "name": "Bisola Adams",
    "dob": {
        "year": 1989,
        "month": 9,
        "day": 10
    },
    "location": "Lagos, Nigeria"
}
###

PATCH http://localhost:3000/v1/user/5d77e850f35d0a11e80b9004
Content-Type: application/json


{
    "name": "Bisola Nneka Adams",
    "dob": {
        "year": 2016,
        "month": 12,
        "day": 7
    },
    "location": "Abuja, Nigeria"
}

###

DELETE http://localhost:3000/v1/user/5d77c3087e61d30c8ef81095
Content-Type: application/json

###